service: f1-bot

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  index:
    name: f1-bot
    handler: src/main.handler
    description: F1 Bot Lambda
    memorySize: 128
    timeout: 10
    environment:
      AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
    package:
      exclude:
        - "!node_modules/**"
        - "yarn.lock"
        - "!package-lock.json"
        - "!package.json"
