service: f1-bot

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
          - "s3:PutObject"
          - "s3:DeleteObject"
        Resource: "arn:aws:s3:::f1-bot-channels/*"

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  index:
    name: f1-bot
    handler: src/main.handler
    description: F1 Bot Lambda
    memorySize: 128
    timeout: 10
    environment:
      DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
      STRIPE_API_KEY: ${env:STRIPE_API_KEY}
    package:
      exclude:
        - "!node_modules/**"
        - "yarn.lock"
        - "!package-lock.json"
        - "!package.json"
  stripe:
    name: f1-bot-stripe-webhook
    handler: src/stripe_payment.app
    description: Stripe webhook for F1 Bot
    memorySize: 128
    timeout: 10
    environment:
      DISCORD_TOKEN: ${env:DISCORD_TOKEN}
      STRIPE_API_KEY: ${env:STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    package:
      exclude:
        - "!node_modules/**"
        - "yarn.lock"
        - "!package-lock.json"
        - "!package.json"
